spring:
    application:
        name: spring-boot-pagination-cursor-demo
    datasource:
        hikari:
            conserversenteventsnectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000
        password: postgres
        url: jdbc:postgresql://localhost:5432/info
        username: postgres
    flyway:
        baseline-on-migrate: true
        baseline-version: 1.1
        enabled: true
        locations: classpath:/db/migration
        out-of-order: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                connection:
                    handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
                dialect: org.hibernate.dialect.PostgreSQLDialect
